apiversion: apps/v1
kind: Deployment
metadata:
  name: argotest
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  templates:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
